---
  - name: Teamcity | create application user
    user: name=teamcity comment="Teamcity CI"
    become: yes
    tags:
      - teamcity

  - name: Teamcity | Check if present
    command: test -x {{teamcity_install_dir}}/TeamCity/bin/catalina.sh
    ignore_errors: yes
    register: teamcity_present
    tags:
      - teamcity

  - name: Teamcity |  Create installation directories
    file: path="{{item}}" state=directory owner="teamcity"
    become: yes
    with_items:
      - "{{teamcity_install_dir}}"
      - "{{teamcity_install_dir}}/.BuildServer/lib/jdbc"
      - "{{teamcity_install_dir}}/.BuildServer/config"
    tags:
      - teamcity

  - name: Teamcity |  Get distribution
    get_url: url="https://download.jetbrains.com/teamcity/TeamCity-{{teamcity_version}}.tar.gz" dest="/tmp/TeamCity-{{teamcity_version}}.tar.gz" validate_certs=no
    become: yes
    become_user: teamcity
    when: teamcity_present | failed
    tags:
      - teamcity

  - name: Teamcity |  Unpack distribution
    unarchive: src="/tmp/TeamCity-{{teamcity_version}}.tar.gz" dest="{{teamcity_install_dir}}" copy="no"
    become: yes
    become_user: teamcity
    when: teamcity_present | failed
    tags:
      - teamcity

  - name: Teamcity |  Template systemd
    template: src="{{role_dir}}/templates/systemd/teamcity-server.service.j2" dest="/usr/lib/systemd/system/teamcity-server.service" mode="755"
    become: yes
    tags:
      - teamcity
